In [1]:
import numpy as np 
from sklearn import preprocessing

/home/rohit/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/rohit/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
feature = np.array([[-500.5],
 [-100.1],
 [0],
 [100.1],
 [900.9]])

In [5]:
min_max_scalar = preprocessing.MinMaxScaler(feature_range=(0,1))

In [6]:
min_max_scalar.fit_transform(feature)

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [7]:
minmax_fit_eq = min_max_scalar.fit(feature)

In [13]:
minmax_fit_eq.transform(feature)

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [14]:
std_scalar = preprocessing.StandardScaler(with_mean=0)

In [15]:
std_scalar_eq = std_scalar.fit(feature)

In [24]:
standadised = std_scalar_eq.transform(feature)

In [25]:
standadised

array([[-1.09213007],
       [-0.21842601],
       [ 0.        ],
       [ 0.21842601],
       [ 1.96583413]])

In [28]:
round(standadised.std())

1.0

In [31]:
feature

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [36]:
robust_scalar = preprocessing.RobustScaler()

In [37]:
robust_scalar.fit_transform(feature)

array([[-2.5],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 4.5]])

In [38]:
features = np.array([[0.5, 0.5],
 [1.1, 3.4],
 [1.5, 20.2],
 [1.63, 34.4],
 [10.9, 3.3]])

In [40]:
features.shape

(5, 2)

In [41]:
features_l2_norm = preprocessing.Normalizer(norm='l2').transform(features)

In [42]:
features_l2_norm

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [43]:
preprocessing.Normalizer(norm='l1').transform(features)

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [45]:
features = np.array([[2, 3],
 [2, 3],[2,3]])

In [46]:
interaction_features = preprocessing.PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)

In [47]:
interaction_features.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [48]:
def add_ten(x) : return x + 10 

In [49]:
preprocessing.FunctionTransformer(add_ten).transform(features)

/home/rohit/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


array([[12, 13],
       [12, 13],
       [12, 13]])

In [50]:
import pandas as pd

/home/rohit/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/rohit/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [51]:
df = pd.DataFrame(features,columns={"feature_1","feature_2"})

In [53]:
df.head()

feature_1  feature_2
0          2          3
1          2          3
2          2          3

In [54]:
df.apply(add_ten)

feature_1  feature_2
0         12         13
1         12         13
2         12         13

In [55]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

In [56]:
features,_ = make_blobs(n_samples=10,n_features=2,centers= 1, random_state=1)

In [57]:
features

array([[-1.83198811,  3.52863145],
       [-2.76017908,  5.55121358],
       [-1.61734616,  4.98930508],
       [-0.52579046,  3.3065986 ],
       [ 0.08525186,  3.64528297],
       [-0.79415228,  2.10495117],
       [-1.34052081,  4.15711949],
       [-1.98197711,  4.02243551],
       [-2.18773166,  3.33352125],
       [-0.19745197,  2.34634916]])

In [58]:
features[0,0] = 1000
features[0,1]= 1000

In [59]:
features

array([[ 1.00000000e+03,  1.00000000e+03],
       [-2.76017908e+00,  5.55121358e+00],
       [-1.61734616e+00,  4.98930508e+00],
       [-5.25790464e-01,  3.30659860e+00],
       [ 8.52518583e-02,  3.64528297e+00],
       [-7.94152277e-01,  2.10495117e+00],
       [-1.34052081e+00,  4.15711949e+00],
       [-1.98197711e+00,  4.02243551e+00],
       [-2.18773166e+00,  3.33352125e+00],
       [-1.97451969e-01,  2.34634916e+00]])

In [66]:
outlier_detector = EllipticEnvelope(contamination=.1)

In [67]:
outlier_detector.fit(features)

EllipticEnvelope(assume_centered=False, contamination=0.1, random_state=None,
                 store_precision=True, support_fraction=None)

In [68]:
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [69]:
houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

In [70]:
houses['Outlier'] = np.where(houses['Bathrooms'] < 20,0,1)

In [71]:
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [72]:
houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses["Square_Feet"]]

In [73]:
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

In [75]:
features, _ = make_blobs(n_samples = 50,
 n_features = 2,
 centers = 3,
 random_state = 1)

In [76]:
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])

In [77]:
from sklearn.cluster import KMeans

In [78]:
clusterer = KMeans(3,random_state=0)

In [79]:
clusterer.fit(features)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=0, tol=0.0001, verbose=0)

In [83]:
dataframe.head()

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

In [81]:
dataframe["group"] = clusterer.predict(features)

In [82]:
dataframe.head()

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

In [93]:
import fancyimpute

ModuleNotFoundError: No module named 'fancyimpute'