In [1]:
import numpy as np

In [3]:
row = np.array([1,2,3])

In [4]:
column = np.array([[1],[2],[3]])

In [6]:
print(row)

[1 2 3]


In [7]:
print(column)

[[1]
 [2]
 [3]]


In [8]:
#creating 2x2 matrix ; 

In [13]:
m1 = np.mat([[1,2],[3,4]])

In [15]:
print(m1.shape)

(2, 2)


In [16]:
m2 = np.array([[1,0],[0,0],[3,0]])

In [18]:
from scipy import sparse

In [19]:
m3 = sparse.csr_matrix(m2)

In [24]:
print(m2)

[[1 0]
 [0 0]
 [3 0]]


In [26]:
m1 = np.array([[1,2,3],[3,4,5]])

In [27]:
add_100 = lambda x: x + 1

In [28]:
vect_add = np.vectorize(add_100)

In [29]:
print(vect_add(m1))

[[2 3 4]
 [4 5 6]]


In [32]:
print(np.std(m1))

1.2909944487358056


In [33]:
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


In [34]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
matrix.diagonal()

array([1, 5, 9])

In [37]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])


In [39]:
np.dot(vector_a ,vector_b)

32

In [40]:
np.random.seed(0)

In [41]:
np.random.randint(0,11,3)

array([5, 0, 3])

In [42]:
%config IPCompleter.greedy=True


In [43]:
np.random.normal(0.0,1.0,3)

array([ 0.07085926,  0.07304142, -1.42232584])

In [44]:
np.random.logistic(0.0,1.0,3)

array([-0.8590656 , -2.81136755, -0.98118713])

In [45]:
np.random.uniform(0.0,1.0,3)

array([0.47766512, 0.81216873, 0.47997717])